# postgres
dsn: postgresql://root@localhost:26257?sslmode=disable
#dsn: host=127.0.0.1 port=5432 user=root password=pg-pwd dbname=postgres  sslmode=disable

# redis
redis_host: 127.0.0.1
redis_port: 6379
redis_pwd: redis-pwd

# Oss
aliyun_oss_accesskey: "不告诉你"
aliyun_oss_accesskey_secret: "不告诉你"

# Log Service
aliyun_log_endpoint: "略"
aliyun_log_accesskey: "略"
aliyun_log_accesskey_secret: "略"

# Wechat Offical Account
woa_appid: "略略略"
woa_app_secret: "略略略略"